### PR TITLE
Decouple emotion from react implementation

### PR DESCRIPTION
**Pull request by cdonohue**
`createUtilitiesFromConfig` uses `emotion` to power the `styleWith` function for the framework-agnostic version. This behavior should be decoupled so the `ConfigProvider` does not need to depend on `emotion`.
> https://github.com/cdonohue/benefit/blob/master/src/createUtilitiesFromConfig.js#L1

The `jsx` pragma and `Box` components are leveraging `@emotion/core` so we should be fine.

Example of witnessed coupled behavior
> https://codesandbox.io/s/jolly-goldberg-hsmfz

### CODE REVIEW

**Comment by cdonohue** [comment]
@ericclemmons I'd love some feedback here if you can. I figure we can bounce ideas around until this feels right.

**Comment by cdonohue** [comment]
After sleeping on things a bit, I think it makes more sense to just simplify generating the utilities and adding things like `styleWith` and `cx` to the vanilla (agnostic) export target only.

**Comment by ericclemmons** [comment]
Should we be worried about this warning?
> No name was provided for external module '@emotion/core' in output.globals – guessing 'core'

**Comment by cdonohue** [comment]
Correct!

**Comment by cdonohue** [comment]
> Should we be worried about this warning?
> 
> > No name was provided for external module '@emotion/core' in output.globals – guessing 'core'

https://github.com/developit/microbundle/issues/223

**Pull request merged**
