### PR TITLE
benefit/react

### PR DESCRIPTION
**Pull request by ericclemmons**
This separates `Box`, `ConfigProvider`, `ConfigConsumer`, & `jsx` into `benefit/react`, so that all non-React exports are just in `benefit`.

There's a test failing currently (`yarn test`) that is confirming the exports for `benefit` and `benefit/react`.

**It fails**, because `require('benefit/react')` has no way of looking for `./dist/react.js`.

This is what caused me to move `jest-preset` (for `require('node-recorder/jest-preset.js')`) to the root:
> https://github.com/ericclemmons/node-recorder/blob/master/jest-preset.js

I tried https://github.com/zkochan/package-preview, but it didn't help with this.

### CODE REVIEW

**Comment by ericclemmons** [comment]
What I'd like to do is attempt `np --content=dist`, but that will require testing a published version.

**Comment by cdonohue** [comment]
Thanks for this 🙏 @ericclemmons !

I'll pull this down soon and take a look.

**Comment by cdonohue** [comment]
Thanks for bringing this example to life @ericclemmons ! Everything here should be solved for as of https://github.com/cdonohue/benefit/releases/tag/v0.2.10

**Comment by ericclemmons** [comment]
But now I don't have any commits :(

**Pull request closed without merging**
