### PR TITLE
Tests for Tailwind compatability

### PR DESCRIPTION
**Pull request by ericclemmons**
- [x] Test coverage.
- [x] Test rule equivalency.

The general approach is:

1. Inject `tailwind.min.css`.
1. Get all `cssRules`.
1. Pluck the `selectorText`.
1. Compare those to `benefit()`'s exported classes.

Prior art:
> https://github.com/ericclemmons/css-inspector/blob/ee1b03c96c3493af8f6b81ce6b6b1bbebeb46b7a/src/stores/cssRules.js

I hope that I can use something "simple", such as https://github.com/testing-library/dom-testing-library, but it may be necessary to use a headless equivalent.

### CODE REVIEW

**Comment by ericclemmons** [comment]
Got the initial scaffolding in place, but I found that #9 is a blocker: _because I'm testing `tailwind.css`, it's best for me to use the same method to test `benefit.css`.

This is primarily because `benefit().utilities` are an object and not `CSSRules` that I can directly snapshot or compare.

**Comment by ericclemmons** [comment]
Once #8 is merged down, both Tailwind & Benefit can have their `CSSRules` parsed and compared directly, which is the most accurate way:

- [ ] Write a test for "coverage", which won't be 100% initially, but can at least be a snapshot of what's different between the two (https://github.com/jest-community/snapshot-diff) for further parity.
- [ ] Write a test that, given the previous coverage, ensures their CSS declarations match.

**Comment by ericclemmons** [comment]
Fixed the output so it's clear that `benefit.css` and `utilties.css` has been written:

```
$ ./scripts/css.js
> Output /Users/eric/Projects/cdonohue/benefit/dist/benefit.css
> Output /Users/eric/Projects/cdonohue/benefit/dist/utilities.css
```

**Comment by ericclemmons** [comment]
@cdonohue Got the tests we need!  There are two:

1. We at least have the _same `className`s.

2. We have the same _values_.

You can view these by running `yarn test`, or `yarn test --watch`


# 1. `className` parity

Currently failing for mostly `focus:` and `hover:` rules.  It seems to be because the rules defined for benefit are `&:hover { ... }` instead of `:hover` selectors:

```
 ● TailwindCSS › utilities › should exist in benefit

    expect(received).toHaveLength(expected)

    Expected length: 0
    Received length: 649
    Received array:  ["appearance-none", "bg-repeat-round", ...
```

# 2. value parity

I'm using `snapshot-diff` to help make this easy to parse, so ideally we'll see "Compared values have no visual difference".  Instead, we can see that we have different values for mostly colors:

```
● TailwindCSS › utilities › should be the same values in benefit

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `TailwindCSS utilities should be the same values in benefit 1`

    - Snapshot
    + Received

      "Snapshot Diff:
    - Compared values have no visual difference."
    + - First value
    + + Second value
    +
    + @@ -132,11 +132,11 @@
    +     "align-text-bottom": "vertical-align: text-bottom;",
    +     "align-text-top": "vertical-align: text-top;",
    +     "align-top": "vertical-align: top;",
    +     "antialiased": "-webkit-font-smoothing: antialiased;",
    +     "bg-auto": "background-size: auto;",
    + -   "bg-black": "background-color: rgb(0, 0, 0);",
    + +   "bg-black": "background-color: rgb(34, 41, 47);",
    +     "bg-blue-100": "background-color: rgb(235, 248, 255);",
```

**Comment by ericclemmons** [comment]
My guess is that this comes back to _emotion not being the one to generate the rules_.

When inspecting the demos @ https://emotion.sh/docs/introduction, I can confirm that emotion is generating `.css-1h3ivcl:hover` for a property declared with `&:hover { ... }`.

**But, since `css.js` is bypassing emotion, `&:hover` never gets interpreted**.

So, we're back to #10 or an alternative method of generating `css.js`!

For an alternative, we'd want emotion to do the processing, but _keep_ our utility names. 🤔

**Comment by ericclemmons** [comment]
@cdonohue Made some progress!  **Went from 649 missing rules to 348**!

For whatever reason, the `:focus` classes aren't being output, but `:focus-within` is.

**Comment by ericclemmons** [comment]
Fixed it!  Down to **48** missing classes!

**Comment by ericclemmons** [comment]
The other failures are a couple typos (e.g. vertical vs. horizontal) and your colors not matching up with:
> https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js

Almost got it!

**Comment by ericclemmons** [comment]
One of the problems is with `-webkit` prefixes.  The only fix I can find is:
> https://github.com/emotion-js/emotion/issues/798

Or, perhaps I can somehow delete that rule when parsing CSSRule?

**Comment by cdonohue** [comment]
I’d vote to ignore during parsing. Autoprefixing is one more value prop that we get for free that I’d like to keep.

**Comment by cdonohue** [comment]
This might also be a reason for us to use `create-emotion` as outlined in that issue above

**Comment by ericclemmons** [comment]
@cdonohue Merge this stuff! The missing utilities can be added in another PR:
> Screen Shot 2019-05-19 at 12 45 49 PM

**Comment by ericclemmons** [comment]
Only missing these rules:
>     Expected length: 0
>    Received length: 27
>    Received array:  ["bg-repeat-round", "bg-repeat-space", "cursor-default", "items-baseline", "items-center", "items-end", "items-start", "items-stretch", "order-1", "order-2", "order-3", "order-4", "order-5", "order-6", "order-7", "order-8", "order-9", "order-10", "order-11", "order-12", "order-first", "order-last", "order-none", "scrolling-auto", "scrolling-touch", "select-all", "select-auto"]

**Comment by ericclemmons** [comment]
Missing
>     Expected length: 0
>    Received length: 12
>    Received array:  ["bg-repeat-round", "bg-repeat-space", "cursor-default", "items-baseline", "items-center", "items-end", "items-start", "items-stretch", "scrolling-auto", "scrolling-touch", "select-all", "select-auto"]

      72 |     )

**Comment by ericclemmons** [comment]
>    Received array:  ["cursor-default", "scrolling-auto", "scrolling-touch", "select-all", "select-auto"]

**Comment by ericclemmons** [comment]
Ah, `default` is replaced with `""`.

**Comment by cdonohue** [comment]
I wonder if it’s better here to treat the `default` key as generating nothing, rather than having to put an empty string as a key. 

Then, we can generate `cursor` differently

**Comment by cdonohue** [comment]
I don’t recall seeing empty strings in the tailwind config

**Comment by ericclemmons** [comment]
I'd like to revert it.

The problem was that cursor-default is the desired className, but default
is ignored.

Do you know a better way?  I don't know the quirks as well as you do.

**Comment by cdonohue** [comment]
I’ll drop a suggestion here as to how we can get around it

**Comment by cdonohue** [comment]
@ericclemmons I believe this happens because tailwind treats `default` keys specific to the utility, rather than the global way we are doing it with the helper function. 

I see two ways around this:
1. Specifically list out the `cursor`utilities within the specific generator. (This would remove the values from the config, but we could just make sure every possible value is already accounted for)
2. We have an argument for the helper function to treat certain keys in a special way (like `default`). This way, it is declarative As to what will be generated. 

Either way is less magic, it’s whether or not we want to stick to the tailwind config structure.

**Comment by ericclemmons** [comment]
That makes sense!

At the very least, I can leave the generated version and just add that
single rule in the generator.

It'd be 1 additional line vs all the other changes.

**Comment by ericclemmons** [comment]
There we go, this is a bit more explicit, and keeps the original `default` behavior.

Only 4 left!
>     Received array:  ["scrolling-auto", "scrolling-touch", "select-all", "select-auto"]

**Comment by ericclemmons** [comment]
@cdonohue 🎉

```
$ /Users/eric/Projects/cdonohue/benefit/node_modules/.bin/jest --verbose --ci
 PASS  __tests__/benefit.test.js
  benefit()
    ✓ should match snapshot of exports (5ms)

 PASS  __tests__/tailwind.test.js
  benefit/utilities.css
    ✓ should match snapshot (35ms)
  tailwindcss/dist/utilities.css
    ✓ should match snapshot (15ms)
    ✓ should exist in benefit (1ms)
    ✓ should be the same values in benefit (7ms)

Test Suites: 2 passed, 2 total
Tests:       5 passed, 5 total
Snapshots:   3 passed, 3 total
Time:        2.021s
Ran all test suites.
✨  Done in 3.31s.
```

**Pull request merged**
